version: "3.9"
services:
  https:
    container_name: "server"
    image: "zackbrand/https:latest"
    build:
      context: .
    volumes:
      - ./keys:/usr/src/app/code/keys
    ports:
      - "3000:3000"